# Generated by Django 3.0.1 on 2021-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signnow',
            name='page_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
