# Generated by Django 3.0.1 on 2021-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signnow_page_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signnow',
            name='page_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signnow',
            name='pdf_file_now',
            field=models.FileField(blank=True, null=True, upload_to='uploadsignnow/'),
        ),
    ]
