# Generated by Django 3.1.7 on 2021-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='page_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='y',
            field=models.IntegerField(),
        ),
    ]
