# Generated by Django 3.0.1 on 2021-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_signnow_doc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signnow',
            old_name='page_no',
            new_name='page_number',
        ),
        migrations.AddField(
            model_name='signnow',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signnow',
            name='types',
            field=models.CharField(blank=True, choices=[('T', 'text'), ('S', 'signature')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signnow',
            name='x_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signnow',
            name='y_s',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
