# Generated by Django 3.1.7 on 2021-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_signnow_reciever_mailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signnow',
            name='reciever_mailid',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
