# Generated by Django 3.1.7 on 2021-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210328_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='signnow',
            name='page_number_t',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signnow',
            name='x_t',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signnow',
            name='y_t',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
