# Generated by Django 3.1.7 on 2021-04-01 12:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_htmlformsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlformsign',
            name='mobilenum',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='htmlformsign',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
