# Generated by Django 3.1.7 on 2021-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_modified_file',
            field=models.FileField(blank=True, null=True, upload_to='result/'),
        ),
    ]
